### ISSUE TITLE
[Improvement] Security - increase account security with 2fa

### ISSUE THREAD

**Issue by matks** [PrestaShop/prestonbot#136]
In order to be able to work, prestonbot has write access to prestashop repositories. In order to make sure this cannot be used by an attacker we need to increase the account security. Enabling 2FA for prestonbot could be a good solution but would this impact the behavior of prestonbot? What about the API calls it performs, how do they work with 2FA?

**Comment by matks** [comment]
Ping @atomiix

**Comment by atomiix** [comment]
I think it's like our personal accounts, when using a token, there's no 2FA

**Comment by matks** [comment]
If we can confirm this, then let's enable 2fa on prestonbot asap 😄 (friday at 6pm?)
