### ISSUE TITLE
[Refacto] Create a GitHubEvent Resolver

### ISSUE THREAD

**Issue by mickaelandrieu** [PrestaShop/prestonbot#28]
an ex here => https://github.com/symfony/symfony/pull/18510

Pros:
* reduce the logic in controllers
* fail fast in case of security breach

Some inspiration here: https://github.com/Swop/github-webhook-bundle

ping @Swop: I'd like to use your bundle *but* keep my [own parser](https://github.com/Lp-digital/github-event-parser) of Json response (it fits more to my needs), any idea? Or I rely only on the library and I use only the signature validator.

**Comment by Swop** [comment]
I think it's totally ok to have a configuration entry to allow/disallow the View subscriber...

**Comment by Swop** [comment]
BTW, your parser is awesome!
I'm wondering that it's could be a good idea to use it in the bundle in this factory: https://github.com/Swop/github-webhook/blob/master/src/Event/GitHubEventFactory.php

**Comment by mickaelandrieu** [comment]
Yes, I wanted to do my own GithubEventFactory: my only concern is that I don't really want to return a GitHubEvent - I mean, not [your own](https://github.com/Lp-digital/github-event-parser/blob/master/EventType/AbstractEventType.php).

I need to think a little bit about it :)

Good idea for the View subscriber, I can use a compiler pass to use my own and return my event :)

**Comment by Swop** [comment]
Yeah I was thinking switching entirely to `Lpdigital\Github\EventType\GithubEventInterface` or having some kind of bridge...

**Comment by mickaelandrieu** [comment]
Be careful of licences, my parser is GPL3 and yours is MIT... I was also thinking about bridging ahahah !

The easy way: I provide a bundle that bridge with yours and I rewrite the 3 listeners. So, using your bundle and completing with mine will allow some like that:

```php
<?php

namespace AppBundle\Controller;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Lpdigital\Github\EventType\GithubEventInterface;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Swop\Bundle\GitHubWebHookBundle\Annotation\GitHubWebHook;

class DefaultController extends Controller
{
    /**
     * @Route("/webhook", name="webhook")
     *
     * @GitHubWebHook(eventType="push")
     * @GitHubWebHook(eventType="pull_request")
     */
    public function indexAction(GithubEventInterface $gitHubEvent)
    {
        $eventName = $gitHubEvent::name();

        return ['status' => 'success'];
    }
}
```

Also I should provide the payload in all cases, I will complete my interface :)

**Comment by mickaelandrieu** [comment]
@Swop you  may be interested by the update of ``GithubEventInterface``:

```php
<?php

/*
 * Copyright (c) 2015 Lp digital system
 *
 * This file is part of Github Parser library.
 *
 * Github Parser is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Github Parser is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Github Parser. If not, see <http://www.gnu.org/licenses/>.
 */

namespace Lpdigital\Github\EventType;

interface GithubEventInterface
{
    /**
     * @return array array of fields that need to be present to define the event
     */
    public static function fields();

    /**
     * @return string name event
     */
    public static function name();

    /**
     * @param array data array to be set
     *
     * @return bool validation rule
     */
    public static function isValid($data);

    /**
     * @param $data
     *
     * @return GithubEventInterface
     */
    public function createFromData($data);

    /**
     * @return array data of the event
     */
    public function getPayload();

    /**
     * @return \Lpdigital\Github\Entity\Repository
     */
    public function getRepository();
}
```

What do you think ?

**Comment by mickaelandrieu** [comment]
Refactorisation done, I still need to secure and still unsure if I have to use your library, your bundle or to make my own system :/

**Comment by Swop** [comment]
Hi @mickaelandrieu,

Perhaps we could work together to draft few enhancements which could be made on the bundle in order for your bot to benefit from these changes.

I'm currently quite busy because I'm gonna move to a new apartment in a few days, but I will be happy to discuss about it as soon as possible after that.

**Comment by mickaelandrieu** [comment]
@Swop yup sure, don't hesitate to bootstrap a little pr, we can work on it together when you will be available :)
