### ISSUE TITLE
[BUG] Report on Starter Theme doesn't works

### ISSUE THREAD

**Issue by mickaelandrieu** [PrestaShop/prestonbot#48]
Hello,

https://github.com/PrestaShop/PrestaShop/pull/7324/files

This contribution shouldn't add a 'Report on Starter theme" or "waiting for wording" labels, would you mind to take a look @antoin-m ?

Mickaël

PS: you can reuse [this mocked response](https://gist.github.com/mickaelandrieu/e5b411aa34a7f35bf5d97816976598d9):
* actual behavior is that the two labels are assigned;
* expected behavior is none of them should be added.

**Comment by aleeks** [comment]
Noooo ! 
I stole a branch, and it took all the commit
It's ok

**Comment by mickaelandrieu** [comment]
:'( we need a new feature then: remove theses labels when not needed anymore wdyt ?

Good luck :p

**Comment by antoin-m** [comment]
Yeah it happened to me once -> If you change the target branch you may inherit from commits that modify classic's theme and thus Preston adds the label.
Hence it is not a bug but Preston should be able to remove the label as an improvment :)

**Comment by mickaelandrieu** [comment]
go for it my bro, i wont have time this week ^^

**Comment by antoin-m** [comment]
I'll take a look tomorrow ;)
