### ISSUE TITLE
Preston should be able to remove labels on update

### ISSUE THREAD

**Issue by antoin-m** [PrestaShop/prestonbot#49]
For example :

1. I open a PR with a commit that modifies classic
2. Preston adds "Report on StarterTheme" label
3. I update the PR -> it doesn't change classic anymore
4. [IMPROVMENT] Preston should remove the "Report on StarterTheme" label

As suggested here : https://github.com/PrestaShop/prestonbot/issues/48

**Comment by mickaelandrieu** [comment]
Good idea, it will be done in `3.x` branch

**Comment by mvorisek** [comment]
Same for version/branch label, see: https://github.com/PrestaShop/PrestaShop/pull/17288

originally `1.7.6.x` label was added, then the base and the description was changed to `1.7.7.x` branch. The new branch label was added successfully, but the original label remained.
