### ISSUE TITLE
The pull request types are not found anymore

### ISSUE THREAD

**Issue by mickaelandrieu** [PrestaShop/prestonbot#75]
And this make prestonBot pretty much useless :)

**Comment by PierreRambaud** [comment]
Hum weird, when it was working yesterday. Is the server still alive? Look at this PR https://github.com/PrestaShop/PrestaShop/pull/9289 it was good :D

**Comment by mickaelandrieu** [comment]
I don't know, most of the time I have to add labels manually: something is wrong :/

**Comment by PierreRambaud** [comment]
Could be cool to have a log access :D

**Comment by matks** [comment]
Fixed without modifications on our side, I dont remember exactly but I believe this was linked to a failure on github webhooks
